const languages = {
  en: {
    search: "Search",
    searchPlaceholder: "What's Your Movie Mood Today ?",
    close: "Close",
    logOut: "Log Out",
    Play: "Play",
    MoreInfo: "More Info",
    NowPlaying: "Now Playing",
    Trending: "Trending",
    Popular: "Popular",
    Upcoming: "Upcoming",
    TopRated: "Top Rated",
  },
  hin: {
    search: "खोज",
    searchPlaceholder: "आज आपकी मूवी का मूड क्या है ?",
    close: "बंद करें",
    logOut: "लॉग आउट",
    Play: "देखें",
    MoreInfo: "और जानकारी",
    NowPlaying: "अभी चलने वाले",
    Trending: "रुझान",
    Popular: "लोकप्रिय",
    Upcoming: "आगामी",
    TopRated: "टॉप रेटेड",
  },
  spanish: {
    search: "Buscar",
    searchPlaceholder: "¿Cuál es tu estado de ánimo cinematográfico hoy ?",
    close: "Cerca",
    logOut: "Cerrar sesión",
    Play: "Jugar",
    MoreInfo: "Más info",
    NowPlaying: "Jugando ahora",
    Trending: "Tendencias",
    Popular: "Popular",
    Upcoming: "Próxima",
    TopRated: "Los más valorados",
  },
};

export default languages;